---
issues:
  closeComment: false
  daysUntilClose: 7
  daysUntilStale: 90
  exemptLabels:
  - pinned
  - security
  - good first issue
  markComment: 'This issue has been automatically marked as stale because it has not
    had recent activity. It will be closed if false further activity occurs. Thank
    you for your contributions.

    '
  staleLabel: wontfix
pulls:
  closeComment: false
  daysUntilClose: 7
  daysUntilStale: 90
  markComment: 'This pull request has been automatically marked as stale because it
    has not had recent activity. It will be closed if false further activity occurs.
    Thank you for your contributions.

    '
