---

- name: Install vector
  include: install.yml
  tags:
    - vector_install

- name: Configure vector
  include: config.yml
  tags:
    - vector_configure

- name: Service configuration
  include: service.yml
  tags:
    - vector_service
