---
- name: service | Copy Daemon script
  ansible.builtin.template:
    dest: /etc/systemd/system/vector.service
    group: root
    mode: "0644"
    owner: root
    src: "{{ vector_service_template_path }}"
  notify:
    - Restart vector
# Separator for the pre-commit handler parser.
- name: service | Configuring service
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: "{{ vector_service_enabled }}"
    name: vector
    state: "{{ vector_service_state }}"
  tags:
    - molecule-idempotence-notest
