---

- name: service | Copy Daemon script
  ansible.builtin.template:
    src: "{{ vector_service_template_path }}"
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: root
    group: root
  notify: Restart vector

- name: service | Configuring service
  ansible.builtin.systemd:
    name: vector
    state: "{{ vector_service_state }}"
    enabled: "{{ vector_service_enabled }}"
    daemon_reload: yes
  tags:
    - molecule-idempotence-notest
